filegroup(
    name = "kml_files",
    srcs = [
        "KML_Sample.kml"
    ],
    visibility = [
        "//chapters/working_with_collections:__pkg__",
        "//chapters/higher_order_functions:__pkg__",
    ]
)