load ("@dependencies_pytest//:requirements.bzl", "requirement")

package(default_visibility = ["//chapters:__pkg__"])

py_library(
    name = "higher_order_functions",
    srcs = [

    ],
    srcs_version = "PY3"
)

test_suite(
    name = "test_higher_order_functions",
    tests = [

    ]
)