load("@dependencies_pytest//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_test(
    name = "test_pytest",
    srcs = [
        "test_pytest.py",
    ],
    deps = [
        requirement("pytest")
    ]
)